server:
  port: 8761

spring:
  config:
    import: { optional:configserver: }
  cloud:
    config:
      enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false

